Task 4. Add tests and e2e test
Gerasik/NETFLIX-roulette pull request #2
Opened 2020-04-06 23:14 UTC by Gerasik

2020-04-10 21:36 UTC, shpakkdv requested changes

2020-04-10 21:36 UTC, shpakkdv commented on src/App.tsx
> +import SearchContainer from 'containers/Search';
I think just `Search` is good. `SearchContainer` sounds a bit redundant.

2020-04-10 21:36 UTC, shpakkdv commented on src/components/ErrorBoundary/index.test.tsx
> +class Buggy extends React.Component {
Why not just?
```tsx
const Buggy: React.FunctionComponent<{ throwError?: boolean }> = ({ throwError = true }) => {
  if (throwError) {
    throw new Error('An error has occurred in Buggy component!');
  }

  return null;
};
```

2020-04-10 21:36 UTC, shpakkdv commented on src/components/ErrorBoundary/index.test.tsx
> +    throw new Error('An error has occured in Buggy component!');
`occurred`

2020-04-10 21:36 UTC, shpakkdv commented on src/components/Footer/style.module.scss
> +  background-color: $tertiaryColor;
`tertiary` is fancy name :)

2020-04-10 21:36 UTC, shpakkdv commented on src/containers/Body/selectors.ts
> +  return (state.bodyReducer as State).get('moviesResponse');
Why is not your `state` immutable? This is incorrect.

2020-04-10 21:36 UTC, shpakkdv commented on src/containers/Body/selectors.ts
> +  (moviesResponse, searchSortBy) => ({
Better to operate immutable data everywhere. Such way you have inconsistency.

2020-04-10 21:36 UTC, shpakkdv commented on src/containers/Search/models.ts
> +}
Look at `containers/Body` and rewrite these types please in according to your own style
```ts
export namespace Payload {
  export type SetData = Models.MoviesResponse;
}

export namespace Action {
  export type SetData = Models.IAction<Payload.SetData>;
}

export namespace ActionCreator {
  export type SetData = (payload: Payload.SetData) => Action.SetData;
}
```

Also, `payload` is usually object.

2020-04-20 22:57 UTC, shpakkdv approved these changes

2020-04-20 22:57 UTC, shpakkdv commented on src/containers/Body/actions.ts
>  // export const increment: Action. = payload => ({
Why do you need it?

2020-04-20 22:57 UTC, shpakkdv commented on src/containers/Body/index.test.tsx
> +  // it('should return the initial state', () => {
`it.skip`

2020-04-20 22:57 UTC, shpakkdv commented on src/containers/Body/models.ts
> +  export type SetStartData = { type: string };
`export type SetStartData = Models.IAction<void>;`

Or to do something like this:
```ts
export interface IEmptyAction {
  type: string;
}

export interface IAction<T> extends IEmptyAction {
  payload: T;
}
```

```ts
export type SetStartData = Models.IEmptyAction;
```

2020-04-20 22:57 UTC, shpakkdv commented on src/containers/Body/selectors.ts
> +  return (state.get('bodyReducer') as State).get('moviesResponse');
I think the word `Reducer` is redundant everywhere in names of store properties.

2020-04-20 22:57 UTC, shpakkdv commented on src/testData.ts
> +export const testMovie1: Movie | MovieMap = {
No `MovieMap`

2020-04-20 22:57 UTC, shpakkdv commented on src/testData.ts
> +export const testMovie2: Movie | MovieMap = {
No `MovieMap`

2020-04-20 22:57 UTC, shpakkdv commented on src/testData.ts
> +import { fromJS } from 'immutable';
These are mocks. You can rename into `data.mock.ts` or something similar with `.mock.ts` postfix

2020-04-22 20:11 UTC, merged

2020-04-27 20:27 UTC, Gerasik commented on src/containers/Body/models.ts
> +  export type SetStartData = { type: string };
I have errors